# Generated by Django 4.2 on 2023-06-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cointegration_arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255)),
                ('coin1', models.CharField(max_length=255)),
                ('coin2', models.CharField(max_length=255)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zScore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spread', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hedgeRatio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idPair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cointegration_arbitrage.cointegrated_pairs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CloseTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin1', models.CharField(max_length=100)),
                ('amount1', models.DecimalField(decimal_places=16, max_digits=50)),
                ('price1', models.DecimalField(decimal_places=16, max_digits=50)),
                ('profit1', models.DecimalField(decimal_places=16, max_digits=50)),
                ('coin2', models.CharField(max_length=100)),
                ('amount2', models.DecimalField(decimal_places=16, max_digits=50)),
                ('price2', models.DecimalField(decimal_places=16, max_digits=50)),
                ('profit2', models.DecimalField(decimal_places=16, max_digits=50)),
                ('close_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
