# Generated by Django 4.2 on 2023-05-05 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zScore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spread', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hedgeRatio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
