# Generated by Django 4.2 on 2023-05-02 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cointegrated_Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crypto1_ID', models.CharField(max_length=255)),
                ('Crypto2_ID', models.CharField(max_length=255)),
                ('Date_detection', models.DateTimeField()),
                ('Spread', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('z_score', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('hedge_ratio', models.FloatField()),
                ('half_life', models.FloatField()),
                ('last_price_1', models.FloatField()),
                ('last_price_2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Simbolo', models.CharField(max_length=10)),
                ('Rank_Mercado', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
        ),
    ]
